### ISSUE TITLE
엔디안 적용시점

### ISSUE THREAD

**Issue by dimohy** [lukewire129/BytePacketSupport#2]
일반적으로 패킷을 생성할 때 빅 엔디안과 리틀 엔디안을 둘 다 사용하는 경우는 없는데요,
`Append(long...` 등 `Endian` 인자를 받는 것을 삭제해도 되지않을까요?

**Comment by lukewire129** [comment]
좋은 의견 감사합니다! 😄

**Comment by lukewire129** [comment]
패킷을 빅엔디언/리틀엔디언 형태 선택사항과
manual type을 추가할까합니다.

- big
- lttile
- auto

auto의 경우 현재 pc의 엔디안 기준에 맞춰서 작성한다는 의도이며

현재 big/little 처리 역시 무조건 reverse시킨다는 개념이 아닌 little에 맞는 처리, big에 맞는 처리로 변경하면 어떨까싶네요

**Comment by dimohy** [comment]
> 패킷을 빅엔디언/리틀엔디언 형태 선택사항과 manual type을 추가할까합니다.
> 
> * big
> * lttile
> * auto
> 
> auto의 경우 현재 pc의 엔디안 기준에 맞춰서 작성한다는 의도이며
> 
> 현재 big/little 처리 역시 무조건 reverse시킨다는 개념이 아닌 little에 맞는 처리, big에 맞는 처리로 변경하면 어떨까싶네요

https://github.com/lukewire129/BytePacketSupport/issues/4#issue-2206932098 이 내용을 살펴 보시겠어요?

**Comment by lukewire129** [comment]
네 맞습니다..!

여기에 더해 패킷형태를 상위시스템과 통신을 호환성을 높이기 위해 시스템에 상관없이 강제적으로

**빅엔디안 타입의 패킷**과 **리틀엔디안 타입**의 패킷,
이것을 설정하지않고 **현재시스템 기준**으로 만들어주는 타입 으로 설정하면 어떨까 합니다!

**Comment by dimohy** [comment]
> 네 맞습니다..!
> 
> 여기에 더해 패킷형태를 상위시스템과 통신을 호환성을 높이기 위해 시스템에 상관없이 강제적으로
> 
> **빅엔디안 타입의 패킷**과 **리틀엔디안 타입**의 패킷, 이것을 설정하지않고 **현재시스템 기준**으로 만들어주는 타입 으로 설정하면 어떨까 합니다!

패킷은 시스템에 따라 가지 않아야 한다는 것이 제 입장이라...
이런 방법은 어떨까요? 패킷 된 바이트 배열 중 첫번째 바이트를 패킷 정보로 두고, 이곳에 패킷이 리틀 엔디안인지 빅 엔디안인지를 정보를 저장하는 것은 어떨까요?

UTF-16의 BOM(Byte Order Mark)이 이런 방법을 택합니다. 빅 엔디언의 경우 `FEFF`로 시작하고 리틀 엔디언인 경우 `FFFE`로 시작합니다.

다만 이 방식의 경우 특정 패킷을 수용하는 장치등에는 활용될 수 없을텐데요, 그런 장치들 (PLC 등)이 빅 엔디언을 많이 사용하는지라 default = little이 아닌 default = auto 가 어떤 의미가 있을지는 잘 모르겠어요.

**Comment by lukewire129** [comment]
Auto 라는 개념을 넣었던 이유는
앱 테마모드에서 Light, Dark, 시스템모드 이렇게 세 분류로 나뉘어져 있는데 패킷빌더 역시 
적용하면 어떨까 하는 생각에 착안했던거였습니다.

앱 테마모드와 달리 PacketBuilder의 경우 사용자 개인에 포커싱되는것 이 아니라
상위/하위 시스템과의 프로토콜의 일종이라는 것을 배제하고 생각을 했었네요 :)

말씀하신대로 의견 수렴해서 Auto는 그땐 그랬었지에 대한 히스토리로.. 👍

**Comment by dimohy** [comment]
뭐 정답이 있겠어요, 살펴보시고 합당한 것을 선택하시면 되어요. 제가 과거에 장비 연동 전문 소프트웨어 회사를 꾸렸었어서 반가운 프로젝트입니다.

**Comment by lukewire129** [comment]
위 의견과 다른 원래 주제에 맞는 얘기를 공유드리고자 합니다.

PacketBuilder의 Append와 
확장메서드의 Append는 

PacketBuilder의 경운 하나의 패킷을 정형화에 맞게 설계에 포커싱 되어있다면, 확장메서드의 Append는 
오로지 사용하고자 하는 사람의 마음대로 쓸 수 있다는 것에 포커싱에 맞추자는 컨셉을 
가져가보면 어떨까 하는 생각이 드네요!

그렇기 때문에  PacketBuilder의 Append에선 Endian은 삭제되지만 확장메서드의 Endian은 Endian Enum값이 아닌 bool값으로 LittleEndian인지에 대한 true, false값으로 처리하면 어떨까 하네요! 


p.s 일반적으로 Intel Cpu의 경우 기본 값은 LittleEndian이기에 false구요!

**Comment by lukewire129** [comment]
> 뭐 정답이 있겠어요, 살펴보시고 합당한 것을 선택하시면 되어요. 제가 과거에 장비 연동 전문 소프트웨어 회사를 꾸렸었어서 반가운 프로젝트입니다.

엄청난 관심에 너무 기분이 좋습니다.
