### ISSUE TITLE
엔디안 Reverse 적용 대상

### ISSUE THREAD

**Issue by dimohy** [lukewire129/BytePacketSupport#3]
제가 알기로 byte[] 및 string 은 엔디안에 상관없이 동일한 것으로 알고 있는데요. reverse할 필요가 없어 보이는데 살펴보시겠어요?

**Comment by lukewire129** [comment]
네 
부랴부랴 인터넷으로 찾아본 바로 
맞는 말씀이십니다

출근동안 관련내용을 좀 봐보겠습니다 😃

**Comment by lukewire129** [comment]
https://devjh.tistory.com/22

우선 array와 string으로 뒤집어놓은건 복구하고 정수형에 대한 건만 처리하도록하겠습니다!
